version: '3'
services:
    db:
        image: postgres:12.2
        volumes:
            - ./tmp/db:/var/postgresql/data
        environment:
            - POSTGRES_USER=alexanderdewhirst
            - POSTGRES_PASSWORD=
        ports:
            - "5432"
    web:
        build: .
        image: alexanderbdewhirst/docker_rails_app_web
        command: bash -c "rm -f tml/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"
        environment:
            - PGHOST=db
            - PGUSER=alexanderdewhirst
        volumes:
            - .:/myapp
        ports:
            - '3000:3000'
        depends_on:
            - db
